name: my-dns-server
services:
  app: 
    image: 'my-dns-server:latest'
    depends_on:
      - mongodb
    build:
      context: ./app
    container_name: app
    ports:
      - 3000:3000
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: dns
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root-secret
      MONGO_USER: user
      MONGO_PASSWORD: user-secret
    ports:
      - 27017:27017
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  # redis
